### ISSUE TITLE
Prepare TripGo APIs for initial candidate recommendation (0.1)

### ISSUE THREAD

**Issue by brylie** [maas-alliance/apis#1]
The TripGo API contains many of the components we have already identified as crucial for supporting the MaaS ecosystem. We can build a MaaS APIs 0.1 from that existing work.

# Task
- prepare the TripGo API for general publication
- remove SkedGo specific branding
- remove overly-complicated endpoints that are not crucial to a 0.1 MaaS APIs release, such as the travelling tourist endpoints
- publish API documentation to this repository in OpenAPI Specification format

**Comment by nighthawk** [comment]
We're on this. Taking the opportunity to incorporate the feedback that we've received from developers who are using our API.

WIP can be followed and commented on here: https://github.com/skedgo/maas-apis/pull/1

**Comment by nighthawk** [comment]
This has been merged.
