### ISSUE TITLE
Take Apache incubation process as model for MA and adapt it to MA needs

### ISSUE THREAD

**Issue by brylie** [maas-alliance/apis#22]
We need a process to incubate our API specifications. To this end, we can adopt *parts* of existing incubation process, such as the Apache incubation process. **Note:** we want our process to be simple, and with low friction, so that we can deliver the initial version of our APIs ASAP. We can then iterate on subsequent versions with feedback from broader stakeholders.

**Comment by evermassen** [comment]
For the MA balloting procedure one additional step is added which deals with the acceptance of a new idea or API. This step is concluded by means of an “Acceptance Ballot”. After passing the “Acceptance Ballot” the incubation phase is started. During this phase, the new idea/API is tested and reviewed by the T&S workgroup. This phase is concluded by yet another vote, the “Release Vote”. A release vote marks the final acceptance of the idea/API.
