### ISSUE TITLE
Review of the proposal made by Sony

### ISSUE THREAD

**Issue by evermassen** [maas-alliance/apis#44]
Review the proposal made by Sony according to the fast track balloting procedure. Please contact Sony directly for additional questions or comments (Mr. Takashi Togame or Mr. Teemu Pohjola.

**Comment by brylie** [comment]
@evermassen, can you post a link to the PDF in this issue, so our collaborators can review?

**Comment by evermassen** [comment]
Hallo Brylie,

Normally you should have received this document as an attachment to the minutes of meeting mail.

Br,

Erwin

**Comment by evermassen** [comment]
Proposal accepted for further development during the conference call of 22/05. Workgroup members are invited to further elaborate on the proposal with Sony directly.
